linters:
  enable:
    - cyclop
    - errcheck
    - gofmt
    - goimports
    - revive
    - gosec
  disable:
    - unused

run:
  timeout: 10m

linters-settings:
  gosec:
    severity: high
  cyclop:
    max-complexity: 10
  errcheck:
    check-blank: false
  gofmt:
    simplify: false
  revive:
    severity: error
    enable-all-rules: false
