apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-radar-deployment
  labels:
    app: weather-radar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-radar
  template:
    metadata:
      labels:
        app: weather-radar
    spec:
      containers:
        - name: weather-radar
          image: weather-radar
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

