name: Go CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  GO_VERSION: 1.23.2
  GOLANGCI_LINT_VERSION: v1.60

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: go build -v ./...

      - name: Run Unit tests
        run:  go test -v -coverprofile coverage.out ./...

      - name: Show coverage summary
        run: |
          go tool cover -func coverage.out

  lint-format:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: ${{ env.GO_VERSION }}


      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

      - name: Run formatter
        run: |
          go fmt ./...

      - name: Check for security issues
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -severity medium ./...